# development environment

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.2:3307/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  jpa:
    #控制台显示sql
    show-sql: true
    #配置自动建表：updata:没有表新建
    generate-ddl: true
    database: mysql
