# development environment
server:
  port:8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.130:3306/rain?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    #控制台显示sql
    show-sql: true
    #配置自动建表：updata:没有表新建
    generate-ddl: true
    database: mysql
    hibernate:

